version: "3.9"

networks:
  guac_network:
    driver: bridge

services:
  guacweb:
    build: .
    container_name: guacweb
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - guacd
    networks:
      guac_network:
  guacd:
    container_name: guacd
    image: guacamole/guacd
    volumes:
      - ./guacamole/guacd.conf:/etc/guacamole/guacd.conf
    ports:
      - "4822:4822"
    restart: on-failure
    networks:
      guac_network:
